### ISSUE TITLE
[Feature Request]  Store Pausing in SQL Database with Timestamp

### ISSUE THREAD

**Issue by TandelK** [PhlexPlexico/get5-web#103]
Just store all the individual pauses done in matches to SQL in pauses section with each TimeStamp of them.

**Comment by Iwhite67** [comment]
Ty

**Comment by PhlexPlexico** [comment]
I have a question, and not bashing or anything, but why would this data be necessary on the webpanel? I personally don't see why there would be a need for that data specifically...

**Comment by Iwhite67** [comment]
Is for know if the match are pause or not

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by PhlexPlexico** [comment]
I mean, I understand that. But why would the match panel need to see if a match is paused? 

Also, when creating a request, please follow the guidelines and fill it out for next time. It's easier for me to organize my thoughts and the necessity of a feature!

**Comment by Iwhite67** [comment]
Actualy, i need to check all 10 serv for view if nobody have need help.

With pause, i know directly what serv check for view if he need heko

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by PhlexPlexico** [comment]
Okay, well considering this is a larger change (requires modifying the apistats plugin even further), I probably won't be working on this, as I'm basically freezing development and working on my own client, away from this fork. PRs are welcome for this change, and here's what will be required to change:
- Find out if there is even a forward that exists in Get5 for `onPause` and `onUnpause`, because I don't believe there is.
- Use the forward to send an API call to the server.
- The server must have an API call (placed in `api.py`) that receives the route and adds the value to the database.
- Speaking of database: a new table must be created in the migration scripts (create a new one via `./manage.py db migrate` and work from there).
- Update the `models.py` to include a new `Pause` model which takes whatever is needed in the database (match id, map id, paused, timestamp). Make sure there's  a DB relation in the `match` or `mapstats` model. Not sure.
- Update the `match.py` to include the new pause model that is returned in either the match page, or the matches page (two different templates).
- `match.html` or `matches.html` template must now add an if statement within to check if the match is currently paused, and add text saying MATCH PAUSED.

That's what I would do at least. And if it isn't included in get5 already, it certainly means it won't be added here as it isn't a top priority.

**Comment by TandelK** [comment]
Also storing pauses in Database will help us in reloading Backup files.

**Comment by PhlexPlexico** [comment]
How would it exactly do that?

**Comment by PhlexPlexico** [comment]
Closing this for now, as there is no event to capture pausing in get5. Once that is included, I'll revisit this.
