### ISSUE TITLE
[Feature Request] Stats Download

### ISSUE THREAD

**Issue by xe1os** [PhlexPlexico/get5-web#110]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
1. Option of uploading teams with respective player id's in web panel using csv or xls.
Example template - teamname,teamtag,logoname,country,player1,player2,player3,player4,player5,player6,publicteam(boolean)

2. Option of downloading match stats into an .xls or csv file from Web Panel.

**Describe alternatives you've considered**
N/A

**Additional context**
1. It will be easier to upload a file from a template rather than manually updating for each team.
2. Downloaded stats can be used in uploading to a different website or application for record/analysis.

**Comment by TandelK** [comment]
I think this will be a good idea for getting teams ready up from Excel Sheet for both Team Upload and Stats Download

**Comment by PhlexPlexico** [comment]
Provided testing can be done for the PR that's been up for some dependency updates, I'll look into this. Found another bug with file uploads, and would not like to go through that whole ordeal again. I think the download would be pretty simple because there is probably a library available, but would you prefer individual stats for a person across the entire platform as well? Or just matches? I'll look into it, but don't expect it to be done anytime soon.

**Comment by xe1os** [comment]
@PhlexPlexico thank you for considering this. Would be great if the stats of both individual and matches are allowed to download.

**Comment by PhlexPlexico** [comment]
I also forgot to mention, there are currently ways of retrieving stats and using some excel magic to convert them to an excel/CSV format, which we do in our small league for Vmix. If you take at /match/:matchid:/scoreboard it produces a JSON object of the entire series, but I'll see what I can do for a CSV export.

**Comment by PhlexPlexico** [comment]
Commit a741812 which is now on the development branch can export CSV from a match, given a map number. It can be accessed via `/match/<int:matchid>/map/<int:mapid>` where 0 is the first map. Please test and confirm if it works alright!
