### ISSUE TITLE
[BUG] Display BO1 Status as 1:0 instead of Match Score 

### ISSUE THREAD

**Issue by TandelK** [PhlexPlexico/get5-web#135]
**Describe the bug**
When there is BO1 Match finished the Status on the Panel is displayed with Score of the match while other Mods like BO3 and other have Maps Won status. For BO3 it will show 1:2 or 2:0 . 

**Which Build**
Master

**To Reproduce**
1. Create a Match with BO1
2. After the match is finished look the panel Matches pages it will display Match Score not Series score. 

**Expected behavior**
It should clearly show the info as 1:0 as other format have to related with Series Type score. This makes confusion for public as thinking how many matches were played.

**Comment by PhlexPlexico** [comment]
This isn't a bug and is working as intended. The whole point of showing scores as the actual map score is intended for quick lookups on the match page. This is intended and I'm going to leave as is, since I prefer having more critical information displayed on the matches page than having to click into a 1-0 match simply to see the score.
