### ISSUE TITLE
[QUESTION]  How is KDA considered

### ISSUE THREAD

**Issue by Fortage** [PhlexPlexico/get5-web#139]
Maybe I don’t understand something, but how is KDA considered? I have 262 kills 232 death in a person and get5 writes 1.25 KDA. After all, KDA should be ~ 1.13. And so with all users.

Which Build
Master

**Comment by PhlexPlexico** [comment]
Hey,

If you hover over the title on the ranking screen, you'll see it's actually Kill/Death Average, not Kill/Death/Assist. This number is brought by all the kill death averages within the system, and averaged out to give a more insightful look on the averages. After all, most of that data is either a combination of averages, or just totals. If you would like, it's easy to calculate the K/D Ratio on that page by hand, that's why I aggregated all K/D and averaged them out.

**Comment by Fortage** [comment]
Thank you, I realized my mistake
