### ISSUE TITLE
./manager.py db upgrade issue

### ISSUE THREAD

**Issue by gouyeh** [PhlexPlexico/get5-web#168]
I am facing this issue after enter ./manager.py db upgrade command.
Using Centos7, Vestacp with nginx+apache and mariadb.

./manager.py db upgrade
Traceback (most recent call last):
  File "./manager.py", line 3, in <module>
    import get5
  File "/var/www/get5-web/get5/__init__.py", line 28, in <module>
    import util
  File "/var/www/get5-web/get5/util.py", line 5, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher

**Comment by PhlexPlexico** [comment]
Cause and effect of #169

**Comment by gouyeh** [comment]
I am using splewis get5-web currently on my server and its working perfect.
If i copy my old **venv** folder from splewis get5-web to Your get5-web version i didn't face any error using **pip install -r requirements.txt** (all completed successfully).
Only getting error when upgrading it **./manager.py db upgrade** this command showing the error which i mention here. 
This error is not related to #169

**Comment by PhlexPlexico** [comment]
It's very much related, because you shouldn't copy paste a virtualenv to another project that has different requirements. Please make sure the setup runs fine, without copy pasting, and then try this. I've only tested this on Raspbian and Ubuntu, so I cannot provide support for CentOS, minus googling things.
