### ISSUE TITLE
[QUESTION] Cloudflare, Https

### ISSUE THREAD

**Issue by gouyeh** [PhlexPlexico/get5-web#181]
Hello, this plugin support ssl?

**Comment by PhlexPlexico** [comment]
https://github.com/PhlexPlexico/get5-web/wiki/Installation#11-optional---move-to-ssl In the wiki it states that you can use SSL/HTTPS. However, you still need a direct HTTP link due to limitations with SteamWorks.

**Comment by gouyeh** [comment]
> 
> 
>you still need a direct HTTP link due to limitations with SteamWorks.
This what i need to be work :(

**Comment by PhlexPlexico** [comment]
So yeah, it's not going to work. 

For future reference, I've moved the plugin to a different project - https://github.com/PhlexPlexico/get5-webapi

There are a few different extensions that deal with HTTPS, but I'm not sure about CloudFlare, since you do need an open endpoint past that (rate limiting is dealt with by the API, you can browse the code to see). I may poke around with a few different implementations and see what can be done.

As for the interim, it would be possible to play around with your web server settings to allow HTTPS on everything, but exclude a few URLs as well (take a look in `get5/api.py` to see the URLs) from redirecting to port 443/CloudFlare and it should, in theory, work.

**Comment by TandelK** [comment]
@PhlexPlexico  if we move to sourcemod cURL can we do both the functions in single extension , HTTPS and FTP Uploads ?

**Comment by PhlexPlexico** [comment]
That would also take an entire rewrite of the plugin (which, as I said, is now in it's own repo). PRs are welcome for that, and leave the request in the other repo, thanks!
