### ISSUE TITLE
[Feature Request] Add CVARs section for manual input while creating matches like config file

### ISSUE THREAD

**Issue by TandelK** [PhlexPlexico/get5-web#182]
While creating a match from panel there are no cvars can be send via the Web Panel. Can we add a text area where we can set cvars and send it to the CSGO server like we have option in match.cfg or match.json for Get5 Config file of "cvars" section ? It will be cool feature to implement regarding custom cvars to set. 

Reference - https://github.com/splewis/get5/blob/e29277b528b8e1a1586bf7aa0107a100c51e4105/configs/get5/example_match.cfg#L80

**Comment by PhlexPlexico** [comment]
Wouldn't want to implement this personally, as the match page has grown to be a big enough beast on its own. 

If someone wanted to make a PR, I wouldn't be opposed. And the steps I would take would be:
1. Create new database table (and migrate)
2. Make additional modal/page that has "match cvars" and input the format as JSON.
3. Store that JSON as string in new table with reference to match ID.
4. Add the query to the `build_match_dict` call and append as needed.

Since this project is approaching EOL in the next 6 days, this is something that would require more testing than time allows.
