### ISSUE TITLE
[BUG] Backup allowed to restore after match completed.

### ISSUE THREAD

**Issue by TandelK** [PhlexPlexico/get5-web#185]
**Describe the bug**
After the Match was completed , tried to restore backup this was just for testing purposes and saw a major issue. I tried to restore to the last round and on the end of the screen of the match the game started with round and also bugging the screen. 

**Which Build**
development

** Expected Behaviour**
If match is ended dont allow Admin Functions to reload backup

**Comment by PhlexPlexico** [comment]
Please define what you mean by "bugging the screen". If it's anything to do with the game itself, it won't effect the web-panel, as it reports the game as finished (via end-time, and a few other factors that can be observed through `api.py`). Sure, you can restore that round if you'd like, but it won't affect the data in the web panel. This isn't really a bug, as it's more of the game functioning as it should.

**Comment by PhlexPlexico** [comment]
Additionally, there is nothing that can be done database side, as the server has yet to report that the match is completed (super_admin_check checks to see if the match is cancelled or finalized).

**Comment by TandelK** [comment]
Does panel shows as tied if the the match went into Overtime ? I thought it was caused by issue of this. Need to check this.

**Comment by PhlexPlexico** [comment]
No, since the plugin on the server will not report the match as completed.
![image](https://user-images.githubusercontent.com/3514085/70626336-d9956d00-1be9-11ea-986b-d1c92943ae75.png)

**Comment by TandelK** [comment]
![Capture](https://user-images.githubusercontent.com/13623158/70685724-3d926100-1cd0-11ea-9697-93a9775bb73d.PNG)

I did round restore at the end of the match after the Game was already over. I think the status got changed from Win to Tied in this.

**Comment by PhlexPlexico** [comment]
At the end of the day, the match reports what the match reports. I'm sure there's a delay for when the match ends in get5 vs. when it actually finishes, and that's so you are able to do things as such. As an example, if the last round didn't play out due to issues, they could still restore. 

This inherently isn't a bug with the web panel, and would be more of an issue with get5 itself, or the API plugin, as to what it reports when the match is complete. The web panel is just accepting it and taking the data it retrieves and making adjustments as needed.
