### ISSUE TITLE
[Feature Request] Round backup files to be available on Web Panel

### ISSUE THREAD

**Issue by xe1os** [PhlexPlexico/get5-web#187]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A way where get5 backup files are uploaded on web panel so that we can restore any round of any given match using web panel. This could be helpful when the csgo server machine fails to start during the live game. We then can restore the round backup to other alternate server.

**Describe alternatives you've considered**
Auto upload of get5 round backup files on web panel. 

**Additional context**
Would be great if download option is also provided to download the backup files on a pc.

**Comment by PhlexPlexico** [comment]
Duplicate: https://github.com/PhlexPlexico/get5-web/issues/26

I already said no to this due to the amount of times server performance actually happens. I've thought about different ways and it all has to do with the plugin, since there's an action that would need to be called every round end. If you would like, please create a ticket in the plugin repository, and not here. (https://github.com/PhlexPlexico/get5-webapi)

It's highly unlikely I'll make this change though, as I did run into a bunch of other issues when attempting this in the first place.
