### ISSUE TITLE
[QUESTION] Setting up with NGINX

### ISSUE THREAD

**Issue by YungGhost1377** [PhlexPlexico/get5-web#188]
Hello, how to start using nginx? I can not do it

**Comment by PhlexPlexico** [comment]
Hi,

I've never used NGINX with WSGI applications (Python Web Apps). So I have no clue. I would assume following this [guide to setup uWSGI on NGINX may help](https://www.digitalocean.com/community/tutorials/how-to-deploy-python-wsgi-applications-using-uwsgi-web-server-with-nginx).

I've only deployed this on Apache because I couldn't be bothered to learn some more NGINX configs.

**Comment by PhlexPlexico** [comment]
No response for the past month. Going to close now. If you come across anything, let me know!
