### ISSUE TITLE
Public Servers 

### ISSUE THREAD

**Issue by shaikhnedab** [PhlexPlexico/get5-web#190]
Anyway to make the servers publicly available? What i mean is anyone with login access to the site can create a match on the publicly available servers.

**Comment by PhlexPlexico** [comment]
Yes - if you are a super-admin in your console, you can flag a server as "publically usable server". This will obviously give away the IP, but it should still mask the RCON password, since super-admins and owners can only use it.

![image](https://user-images.githubusercontent.com/3514085/72349852-eacb1100-36a2-11ea-8733-2a0ad388180e.png)


Also while this app is technically "complete", I would highly recommend using [get5-web-go](https://github.com/FlowingSPDG/get5-web-go) as it contains _most_ features from this web panel - barring demo uploads and showing vetoes I believe. It's faster, and much more up to date.

**Comment by shaikhnedab** [comment]
Thanks for your fast response and Kind suggestion. I will try the Go version.

**Comment by PhlexPlexico** [comment]
Sounds good. I'll close this ticket now. If you need anything else, feel free to open a new one!

**Comment by shaikhnedab** [comment]
Thanks again :)
