### ISSUE TITLE
autojoin to team (CT/T)

### ISSUE THREAD

**Issue by MikkelDK** [PhlexPlexico/get5-web#49]
Hey @PhlexPlexico - 

It's nice to see, you are doing dev continue/extra settings for get5 (incl web.)

I couldn't make an "issue/question via get5 repo from your GitHub, so I try ask here.

Do you think, there is "autojoin"?
As example:
Team1 + Team2 added with "STEAMID64" via web.
Creating match > Team1 + Team2 joined the server = automatic joined to the team of CT/T e.g?

Let me hear from you!
And keep the work! ;)

/Mikkel

**Comment by PhlexPlexico** [comment]
Hey Mikkel!

I believe there is already an option for this `get5_check_auths` in the get5 plugin already. This ensures the SteamID tied to a team will have the person force-join that team. Since I'm using the webpanel for a more competitive state, I actually set that each time I launch a match, so that the config files do not matter on the server, as seen [here](https://github.com/PhlexPlexico/get5-web/blob/master/get5/match.py#L218) :)

As for the get5 repo, I only forked it so I could make a small PR for allowing users custom names to update. Once/if that is accepted, I'll be deleting it from my repo. All the scripting work that I do will be in this repo as well, since I plan on building on the API stats plugin as well!

Thanks!

Phlex

**Comment by MikkelDK** [comment]
Hey Phlex,

Sounds cool with the new thing.

Before I will do use your "version" just for check it out/testing as example! ;) 

Are you planned to update the API stats (for the get5-web) so it's possible to see more stats, like from ingame? as example: K/D, ADR, UD, EF. (if possible)

**Comment by PhlexPlexico** [comment]
I recommend opening this up in Firefox, but I did create an API call just for this!
http://csgo.sklesports.ca/match/19/scoreboard for an example here.

Basically, I grab all the information as it gets updated from the database, and return it as a JSON format, since we are feeding this into a spreadsheet which is then read by some broadcasting software and converted to a nice little graphic that we display on stream :) which can actually be seen at this timestamp: https://www.twitch.tv/videos/411281233?t=35m09s

I think, aside from some massive code cleanup from the terrible things I created, I am going to probably improve on the veto (instead of showing just pick ban, also show what side was selected), and then go from there, see what else I need. 

I hope this helps! I'd recommend looking at the `match.py` mainly, as that's where the logic for the scoreboard call was made, and inside `models.py` since I've made quite a few chanegs.

**Comment by MikkelDK** [comment]
Ah cool.

Are you using it to tournament as example? 

Dunno, about you are planned, for the get5 support as an example toournament.com I know, there is eBot, but I will mean Get5 is better. :)

**Comment by PhlexPlexico** [comment]
I was thinking about looking into Toournament functionality for later, once I get more experience with flask here. That may take awhile!

And yup! We've been using it for our League (that's been posted above) and any future tournaments that may be held :) 

But for now, I'm going to finish what's on the issues list here, and then probably get Toournament APIs into place, it shouldn't be too bad to add in, either, the more I think about it! But yeah, feel free to play around with it! There's a few changes here and there but it should mostly be the same as when I first laid my hands on this project!

**Comment by MikkelDK** [comment]
Im ready to support your project. :) im not coder. But mostly want to support someone, who will try improve with new thing. As an example maybe, Toournament.

**Comment by PhlexPlexico** [comment]
Hey, I'm happy so long as anyone else is using it! Creating feature requests is always a good way to help improve. However, I'll still probably sort priority on what I need/what seems interesting to me, haha.

**Comment by MikkelDK** [comment]
Yeah feature request for idea e.g

Maybe, we will see a possible, to the Toournament API and start match from the get5web.

Create tournament. 
Adding teams. 
Setup seeds.
Starting the tournament. 
Where the match > team vs team can be started via get5web.

I mean it's like what ebot do. But I have already forget how it's do. With the API.

**Comment by PhlexPlexico** [comment]
Hmm I see. So more of an automation tool that will create matches once they're available. I think this can be mostly accomplished, aside from seeds and showing brackets... I'll have to really read into it and understand how it will interact with the webpanel! In the meantime, I've created another issue (#50) to keep track. I'll put your comment in there, so I can keep track of what features should be implemented!

**Comment by MikkelDK** [comment]
Yeah correct.

I will try check, and update you later(tomorrow, it's 2254 here), about the function of API incl Toournament.

**Comment by PhlexPlexico** [comment]
And one last thing - as a very rough replacement for now - there is "Seasons" available, in which you could set a season for a day or two, label it as a tournament, and it actually does have a leaderboard available, which shows wins, losses, and round diffs :)
http://csgo.sklesports.ca/leaderboard/season/1/

**Comment by PhlexPlexico** [comment]
And sounds good! Hope you have a goodnight and thank you very much! Be sure to post it in #50 once you get the chance. I'll close this issue now since it seems to be growing rather large!

**Comment by MikkelDK** [comment]
Ah yep. No problem.

**Comment by MikkelDK** [comment]
Hey, @PhlexPlexico I have forgotten to ask 1 thing:

Is there like that (stats about VETO pick as an example like this):
![](https://i.gyazo.com/36963c50985fe0eedd2a828229ce3e6c.png)

About it taking the "pick/VETO" from ingame?

**Comment by PhlexPlexico** [comment]
What do you mean exactly? How does it get the picks and bans? 

I've modified get5_apistats to add in two new calls `Get5_OnMapVetoed` and `Get5_OnMapPicked` which just sends either ban, pick, or none, the map name, and either team1 or team2 and inside the match it uses a bit of logic to figure out who is who, then inserts the records into a `veto` table (this table is created by running that manager.py command). I hope this helps, if not I'll need more coffee!

**Comment by MikkelDK** [comment]
Ah yeah. So it's post data of pick/ban on web?

**Comment by PhlexPlexico** [comment]
Yup! It's a post request that's sent from get5_apistats :)
