### ISSUE TITLE
[Feature Request] Panel match Stats option Public/Private Match

### ISSUE THREAD

**Issue by TandelK** [PhlexPlexico/get5-web#63]
There should be a option in Create a Match for Public able to see Matches with Stats on the Panel. If Admin select the match is Private than it should not show on the matches section of the panel for all the public. We can have option for only Teams people should be able to see the scores and other information, selecting public should show all the information to the public about the match going on.

**Comment by TandelK** [comment]
@PhlexPlexico If you dont mind i am creating a discord server specially for Get5 purposes. If you would like to join in. https://discord.gg/YttKdSq

**Comment by PhlexPlexico** [comment]
This will require a rework of the authentication if I want this done properly, as so users cannot create matches unless I'm misunderstanding how the whitelist actually works.

In an ideal world - people login with steam and can see the matches then for stats. If not logged in and clicked they get a rendered page that says "Sorry! You are not authorized to view this match"

Another thing would be games in progress - the button to connect and view GoTV would only be enabled if they're within a list of spectators or part of the game setup.

**Comment by PhlexPlexico** [comment]
Another good use case for re-writing security would be for super-admins, who could see/edit all teams and servers. This would only be for exclusive people though, as it does put a huge security risk in those who trust the service, since the super-admins would be able to see rcon passwords, etc. This is in relation to [#151](https://github.com/splewis/get5-web/issues/151) on the original repo.

**Comment by TandelK** [comment]
@PhlexPlexico I would recommend you to add Checkbox for showing Super Admins the RCON Password while adding Servers, if the server is set to Public Usage they should show RCON Password to Super Admins and if they are private , they should be not shown. The option super Admin should have is to keep that server or delete that server .

**Comment by PhlexPlexico** [comment]
Maybe when the match is pending we query the team list to see who is all in the match, and match up the SteamID by logging in? Don't show it or give a 400 error when they are not in the match and the match is pending? Only when the match is started will people be able to see the scoreboard updated.

As for the previously posted issue, we could allow admins to manage everything on the site, and keep the permissions as-is. Since admins already can have the option for access to all matches, they can easily see the rcon_password via sending a command from the admin menu.

**Comment by PhlexPlexico** [comment]
Feature now in testing.
