### ISSUE TITLE
[BUG] Match Stats and veto details not showing

### ISSUE THREAD

**Issue by xe1os** [PhlexPlexico/get5-web#95]
**Describe the bug**
Veto and Match details doesnt show on web panel. Match Shows pending forever.
Tried compiling the get5_apistats from both master and develpment branch. 

**Which Build**
Happening in both master & development builds

**To Reproduce**
1. logged in to http://get5.phlexplexi.co
2. Created a match
3. Readied up players in the game.
4. Rounds started
5. Match shows pending in webpanel
6. No veto and match stats available

**Expected behavior**
Match should show live 0:0 with veto details

**Comment by PhlexPlexico** [comment]
In the get5api.cfg located in cfg/sourcemod/ in your server directory, do you have FTP enabled or disabled?

**Comment by xe1os** [comment]
> In the get5api.cfg located in cfg/sourcemod/ in your server directory, do you have FTP enabled or disabled? Did you finish knife rounds if any?

FTP is Disabled
get5_api_ftp_enabled "0"

**Comment by PhlexPlexico** [comment]
Try enabling it, but leave other options blank and try again, if you don't mind. I think I may have an idea of what's going on. I saw that a previous match had the vetoes go through.

**Comment by xe1os** [comment]
> Try enabling it, but leave other options blank and try again, if you don't mind. I think I may have an idea of what's going on. I saw that a previous match had the vetoes go through.
> 
> EDIT: Also please make sure the `get5_web_api_url` and `get5_web_api_key` do not exist in the config.

@PhlexPlexico tried with get5_api_ftp_enabled "1" still the stats and vetos are not shown. Looks like issue with get5_apistats.smx

I tried changing to splewis get5_apistats.smx plugin. Match shows live and stats are updated.

**Comment by PhlexPlexico** [comment]
I've updated the plugin to remove some of the unwanted configs from the file. Please delete the config and recompile the plugin from dev. 

Are you using the release of get5 or are you using the development build there as well?

**Comment by xe1os** [comment]
> I've updated the plugin to remove some of the unwanted configs from the file. Please delete the config and recompile the plugin from dev.
> 
> Are you using the release of get5 or are you using the development build there as well?
developent build - get5-463
> 
> Oh, and did you by chance install System2 on your server as well?
Yes!

**Comment by PhlexPlexico** [comment]
Alright well I'm going to use the latest build for both apistats and get5 as well. Will get back to you and see what happens. Because I was testing this last night with uploads enabled. I think it may have to do with the API URL not being set when the OnSeriesInit is called.

**Comment by xe1os** [comment]
> Alright well I'm going to use the latest build for both apistats and get5 as well. Will get back to you and see what happens. Because I was testing this last night with uploads enabled. I think it may have to do with the API URL not being set when the OnSeriesInit is called.

@PhlexPlexico just checked with your previous release https://github.com/PhlexPlexico/get5-web/releases/tag/0.11
Works fine!

**Comment by PhlexPlexico** [comment]
Yeah that's because my previous release only has Map Vetoes. The new release includes Demo Uploads via FTP when a match finishes. It's a weird condition when the demo finishes recording that it tosses away the API URL and secret, and it's doing it before the match completes. I'm going to make one more change to development here shortly and tell me if it works for you.

**Comment by PhlexPlexico** [comment]
http://get5.phlexplexi.co/match/13 and http://get5.phlexplexi.co/match/12 I'm not sure what exactly is wrong with the plugin. Maybe its a connection issue, and the server can't reach the game fast enough? I have no clue, as I can't seem to reproduce it at all. I'll attach the version that I'm using, and hope it works. If not, feel free to use 0.11 as it should have no adverse effects on the system other than uploads not working :)
file
[Uploading get5_apistats.zip…]()

**Comment by xe1os** [comment]
> [get5.zip](https://github.com/PhlexPlexico/get5-web/files/3263781/get5.zip)
> [get5_apistats.zip](https://github.com/PhlexPlexico/get5-web/files/3263763/get5_apistats.zip)
> http://get5.phlexplexi.co/match/13 and http://get5.phlexplexi.co/match/14 I'm not sure what exactly is wrong with the plugin. Maybe its a connection issue, and the server can't reach the game fast enough? I have no clue, as I can't seem to reproduce it at all. I'll attach the version that I'm using, and hope it works. If not, feel free to use 0.11 as it should have no adverse effects on the system other than uploads not working :)
> 
> EDIT: And for compatibility sake, I've added the get5 that I compiled a little while ago (May 30) direct from source.

@PhlexPlexico tried this method using your compiled plugins. Does'nt seem to work. Will continue to use 0.11 till this gets sorted. Thanks for your help :)

**Comment by PhlexPlexico** [comment]
Very interesting! And you don't have any other plugins running, correct? You have the MySQL plugins disabled and all? I want to attribute this towards a network/other plugin conflict then, and apologies that I can't really help with that. Maybe try creating a web panel that's local and running through there?

**Comment by dMwJr** [comment]
> [get5.zip](https://github.com/PhlexPlexico/get5-web/files/3263781/get5.zip)
> [get5_apistats.zip](https://github.com/PhlexPlexico/get5-web/files/3263763/get5_apistats.zip)
> http://get5.phlexplexi.co/match/13 and http://get5.phlexplexi.co/match/14 I'm not sure what exactly is wrong with the plugin. Maybe its a connection issue, and the server can't reach the game fast enough? I have no clue, as I can't seem to reproduce it at all. I'll attach the version that I'm using, and hope it works. If not, feel free to use 0.11 as it should have no adverse effects on the system other than uploads not working :)
> 
> EDIT: And for compatibility sake, I've added the get5 that I compiled a little while ago (May 30) direct from source.

Not to steal the thread away but are those plugins that you posted recommended for your changed ge5-web panel? i have not yet recompiled any plugins after upgrading to version .2  web panel but now that i have the panel working would it be a good idea?

**Comment by PhlexPlexico** [comment]
Don't bother with the get5.zip as that is just the latest build from splewis' repository. Those can be found on his, and you probably shouldn't stray from there!

As for the api-stats, yes I would recommend that one since I built it from the development branch as of yesterday. I'll be posting it on the Releases page sometime later today. But if you'd like, download it from here.

**Comment by dMwJr** [comment]
> Don't bother with the get5.zip as that is just the latest build from splewis' repository. Those can be found on his, and you probably shouldn't stray from there!
> 
> As for the api-stats, yes I would recommend that one since I built it from the development branch as of yesterday. I'll be posting it on the Releases page sometime later today. But if you'd like, download it from here.

awesome, thank you.

**Comment by dMwJr** [comment]
so since i didnt compile the plugin myself. What else do i need to change? reading up above that you made changes to adjust config files? For demo uploads what do i need to change? im sure there are FTP settings etc. etc.

also is SMJasson still needed? i never installed that or really knew how

PS. Link broken in your read me to the apache2 + ubuntu install guide

**Comment by MikkelDK** [comment]
> PS. Link broken in your read me to the apache2 + ubuntu install guide
It's here: [Apache2 + Ubuntu Installation Guide](https://github.com/PhlexPlexico/get5-web/wiki/Installation)

**Comment by PhlexPlexico** [comment]
SMjansson is still required. You need to go gather the `.so` extensions and place them in the extensions folder in your sourcemod installation. The same will go for System2, and Steamworks. 

[SMJansson Library](https://github.com/thraaawn/SMJansson/tree/master/bin)
[Latest Steamworks builds](http://users.alliedmods.net/~kyles/builds/SteamWorks/)
[System2](https://github.com/dordnung/System2/releases)

Please refer to the wiki for the rest of the documentation. This is getting off topic from the initial issue. If there is anymore issues with demo uploads, please recreate, or reopen this ticket. If you have any issues with installation, you will have to refer to google because the rest of installation server-side is Sourcemod related installs and you can find plenty of guides.

As for the web-server setup, you can follow instructions from the link @MikkelDK provided. It has the installation notes and the new `prod_config` values that I've added. Thanks.
